server:
  port: 21501

spring:
  application:
    name: user-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ds_user_service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Keycloak Configuration
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:https://keycloak.phuongy.works}
  realm: ${KEYCLOAK_REALM:master}
  client-id: ${KEYCLOAK_CLIENT_ID:dss-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:dss-secret}

# Settings Service Configuration
settings:
  service:
    url: ${SETTINGS_SERVICE_URL:http://settings-service:21502}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.ds.user: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
