# Development-specific configuration for User Service
# This profile is used for local development

spring:
  jpa:
    hibernate:
      ddl-auto: update  # Auto-migrate schema in development
    show-sql: true  # Show SQL in development
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        generate_statistics: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  # Disable Flyway - let Hibernate handle schema management
  flyway:
    enabled: false

# Enhanced logging for development
logging:
  level:
    org.hibernate.SQL: DEBUG  # Show SQL in development
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show parameter values
    com.ds.user: DEBUG  # Show debug logs for user service
