server:
  port: 21500

spring:
  application:
    name: api-gateway
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}

# Service URLs
services:
  user:
    url: ${USER_SERVICE_URL:http://user-service:21501}
  settings:
    url: ${SETTINGS_SERVICE_URL:http://settings-service:21502}
  zone:
    url: ${ZONE_SERVICE_URL:http://zone-service:21503}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.ds.gateway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
