name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  service-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: chmod +x mvnw
      - run: ./mvnw -B -ntp test -Dgroups=service

  grpc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: chmod +x mvnw
      - run: ./mvnw -B -ntp test -Dgroups=grpc

  build:
    runs-on: ubuntu-latest
    needs: [service-test, grpc-test]   # build phụ thuộc cả 2 test
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry  
        if: ${{ !github.event.act }} # skip during local actions testing
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ !github.event.act }} # skip during local actions testing
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/phuongp2003/juiceshop_user:${{ github.run_id }}
            ghcr.io/phuongp2003/juiceshop_user:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
